# Generated by Django 4.0.3 on 2022-07-17 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=15, verbose_name='Programming Language')),
                ('lang_extends', models.CharField(max_length=15)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='code',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=20, verbose_name='File Name')),
                ('code', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor1.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
